package com.pinguino.emotives.manager;

public enum LanguageMessage {
    NO_PERMISSION,
    HELP_HEADER,
    EMOTE_MESSAGE,
    ALREADY_IGNORING,
    PLAYER_NOT_FOUND,
    NOT_IGNORING,
    UNIGNORED_ALL,
    IGNORED_ALL,
    IGNORED,
    UNIGNORED, IGNORE_LIST_HEADER, IGNORE_LIST_ITEM, IGNORING_ALL,
}
